# Generated by Django 4.2.3 on 2023-07-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ineffable_app", "0018_studentform"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentform",
            name="id",
        ),
        migrations.AlterField(
            model_name="studentform",
            name="rollno",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
