# Generated by Django 4.2.3 on 2023-07-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ineffable_app", "0019_remove_studentform_id_alter_studentform_rollno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentform",
            name="centre_code",
            field=models.CharField(max_length=20),
        ),
    ]
