# Generated by Django 4.2.3 on 2023-07-16 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ineffable_app", "0020_alter_studentform_centre_code"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Studentform",
        ),
    ]
