# Generated by Django 4.2.3 on 2023-07-16 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ineffable_app", "0024_studentform"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Status",
        ),
    ]
