# Generated by Django 4.2.3 on 2023-07-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ineffable_app", "0027_delete_status_create"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status_create",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=30)),
                ("student_rollno", models.IntegerField()),
                ("centre_name", models.CharField(max_length=30)),
            ],
        ),
    ]
