# Generated by Django 4.2.3 on 2023-07-18 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ineffable_app", "0029_centrestatus"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CentreStatus",
        ),
    ]
