# Generated by Django 4.2.3 on 2023-07-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ineffable_app", "0031_centrestatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentform",
            name="course_name",
            field=models.CharField(max_length=150),
        ),
    ]
