# Generated by Django 4.2.3 on 2023-07-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ineffable_app", "0032_alter_studentform_course_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="unknown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("A", "Choice A"), ("B", "Choice B")], max_length=100
                    ),
                ),
            ],
        ),
    ]
