# Generated by Django 4.2.3 on 2023-07-21 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ineffable_app", "0033_unknown"),
    ]

    operations = [
        migrations.DeleteModel(
            name="unknown",
        ),
    ]
