# Generated by Django 4.2.3 on 2023-07-30 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ineffable_app", "0036_add_centre_add_students"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="add_students",
            options={},
        ),
        migrations.RemoveField(
            model_name="add_students",
            name="centre_code",
        ),
        migrations.DeleteModel(
            name="Add_Centre",
        ),
    ]
