# Generated by Django 4.2.3 on 2023-07-30 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ineffable_app", "0037_alter_add_students_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Add_Students",
        ),
    ]
