# Generated by Django 4.2.3 on 2023-07-31 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ineffable_app", "0043_alter_add_students_centre_code"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Add_Students",
        ),
    ]
