# Generated by Django 4.2.3 on 2023-07-31 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ineffable_app", "0044_delete_add_students"),
    ]

    operations = [
        migrations.CreateModel(
            name="Add_Students",
            fields=[
                ("Studentname", models.CharField(max_length=20)),
                ("Fathername", models.CharField(max_length=20)),
                ("Mothername", models.CharField(max_length=20)),
                (
                    "rollno",
                    models.BigIntegerField(
                        default=300, primary_key=True, serialize=False
                    ),
                ),
                ("dob", models.DateField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="")),
                ("centre_name", models.CharField(max_length=50)),
                ("duration", models.CharField(help_text="1 month", max_length=20)),
                (
                    "Examination_date",
                    models.CharField(
                        blank=True, help_text="may,2023", max_length=14, null=True
                    ),
                ),
                ("percnt", models.IntegerField()),
                ("grade", models.CharField(max_length=30)),
                (
                    "session",
                    models.CharField(help_text="March 2023-May 2023 ", max_length=50),
                ),
                ("Course_module", models.CharField(max_length=300)),
                ("written_mark", models.IntegerField()),
                ("practical_mark", models.IntegerField()),
                ("assignment_mark", models.IntegerField()),
                ("viva_mark", models.IntegerField()),
                (
                    "centre_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="centre_Code",
                        to="ineffable_app.add_centres",
                    ),
                ),
            ],
        ),
    ]
