# Generated by Django 4.2.3 on 2023-07-31 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ineffable_app", "0045_add_students"),
    ]

    operations = [
        migrations.RenameField(
            model_name="add_centres",
            old_name="centrecode",
            new_name="Centrecode",
        ),
        migrations.RenameField(
            model_name="add_centres",
            old_name="centrename",
            new_name="Centrename",
        ),
        migrations.RenameField(
            model_name="add_students",
            old_name="centre_code",
            new_name="Centrecode",
        ),
        migrations.RenameField(
            model_name="add_students",
            old_name="centre_name",
            new_name="Centrename",
        ),
    ]
